public enum ID_Quests
{
    The_Grand_Harbor__TO__Longstand = 0,
    The_Grand_Harbor__TO__Whitehand = 1,
    The_Grand_Harbor__TO__Jadewing = 2,
    The_Grand_Harbor__TO__Wolfland = 3,
    The_Grand_Harbor__TO__Frostblade_Sanctuary = 4,
    The_Grand_Harbor__TO__The_Tempest_Lair = 5,
    The_Grand_Harbor__TO__Renegade_Hideaway = 6,

    Longstand__TO__The_Grand_Harbor = 7,
    Longstand__TO__Whitehand = 8,
    Longstand__TO__Jadewing = 9,
    Longstand__TO__Wolfland = 10,
    Longstand__TO__Frostblade_Sanctuary = 11,
    Longstand__TO__The_Tempest_Lair = 12,
    Longstand__TO__Renegade_Hideaway = 13,

    Whitehand__TO__The_Grand_Harbor = 14,
    Whitehand__TO__Longstand = 15,
    Whitehand__TO__Jadewing = 16,
    Whitehand__TO__Wolfland = 17,
    Whitehand__TO__Frostblade_Sanctuary = 18,
    Whitehand__TO__The_Tempest_Lair = 19,
    Whitehand__TO__Renegade_Hideaway = 20,

    Jadewing__TO__The_Grand_Harbor = 21,
    Jadewing__TO__Longstand = 22,
    Jadewing__TO__Whitehand = 23,
    Jadewing__TO__Wolfland = 24,
    Jadewing__TO__Frostblade_Sanctuary = 25,
    Jadewing__TO__The_Tempest_Lair = 26,
    Jadewing__TO__Renegade_Hideaway = 27,

    Wolfland__TO__The_Grand_Harbor = 28,
    Wolfland__TO__Longstand = 29,
    Wolfland__TO__Whitehand = 30,
    Wolfland__TO__Jadewing = 31,
    Wolfland__TO__Frostblade_Sanctuary = 32,
    Wolfland__TO__The_Tempest_Lair = 33,
    Wolfland__TO__Renegade_Hideaway = 34,

    Frostblade_Sanctuary__TO__The_Grand_Harbor = 35,
    Frostblade_Sanctuary__TO__Longstand = 36,
    Frostblade_Sanctuary__TO__Whitehand = 37,
    Frostblade_Sanctuary__TO__Jadewing = 38,
    Frostblade_Sanctuary__TO__Wolfland = 39,
    Frostblade_Sanctuary__TO__The_Tempest_Lair = 40,
    Frostblade_Sanctuary__TO__Renegade_Hideaway = 41,

    The_Tempest_Lair__TO__The_Grand_Harbor = 42,
    The_Tempest_Lair__TO__Longstand = 43,
    The_Tempest_Lair__TO__Whitehand = 44,
    The_Tempest_Lair__TO__Jadewing = 45,
    The_Tempest_Lair__TO__Wolfland = 46,
    The_Tempest_Lair__TO__Frostblade_Sanctuary = 47,
    The_Tempest_Lair__TO__Renegade_Hideaway = 48,

    Renegade_Hideaway__TO__The_Grand_Harbor = 49,
    Renegade_Hideaway__TO__Longstand = 50,
    Renegade_Hideaway__TO__Whitehand = 51,
    Renegade_Hideaway__TO__Jadewing = 52,
    Renegade_Hideaway__TO__Wolfland = 53,
    Renegade_Hideaway__TO__Frostblade_Sanctuary = 54,
    Renegade_Hideaway__TO__The_Tempest_Lair = 55,

}
